using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FrontendMentor.InvoiceApp.Data.Migrations;

/// <inheritdoc />
public partial class SeedCountriesTable : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // Insert comprehensive country data
        migrationBuilder.Sql(@"
            INSERT INTO Countries (Id, Name, Code) VALUES
            (NEWSEQUENTIALID(), 'Afghanistan', 'AF'),
            (NEWSEQUENTIALID(), 'Albania', 'AL'),
            (NEWSEQUENTIALID(), 'Algeria', 'DZ'),
            (NEWSEQUENTIALID(), 'American Samoa', 'AS'),
            (NEWSEQUENTIALID(), 'Andorra', 'AD'),
            (NEWSEQUENTIALID(), 'Angola', 'AO'),
            (NEWSEQUENTIALID(), 'Anguilla', 'AI'),
            (NEWSEQUENTIALID(), 'Antarctica', 'AQ'),
            (NEWSEQUENTIALID(), 'Antigua and Barbuda', 'AG'),
            (NEWSEQUENTIALID(), 'Argentina', 'AR'),
            (NEWSEQUENTIALID(), 'Armenia', 'AM'),
            (NEWSEQUENTIALID(), 'Aruba', 'AW'),
            (NEWSEQUENTIALID(), 'Australia', 'AU'),
            (NEWSEQUENTIALID(), 'Austria', 'AT'),
            (NEWSEQUENTIALID(), 'Azerbaijan', 'AZ'),
            (NEWSEQUENTIALID(), 'Bahamas', 'BS'),
            (NEWSEQUENTIALID(), 'Bahrain', 'BH'),
            (NEWSEQUENTIALID(), 'Bangladesh', 'BD'),
            (NEWSEQUENTIALID(), 'Barbados', 'BB'),
            (NEWSEQUENTIALID(), 'Belarus', 'BY'),
            (NEWSEQUENTIALID(), 'Belgium', 'BE'),
            (NEWSEQUENTIALID(), 'Belize', 'BZ'),
            (NEWSEQUENTIALID(), 'Benin', 'BJ'),
            (NEWSEQUENTIALID(), 'Bermuda', 'BM'),
            (NEWSEQUENTIALID(), 'Bhutan', 'BT'),
            (NEWSEQUENTIALID(), 'Bolivia', 'BO'),
            (NEWSEQUENTIALID(), 'Bosnia and Herzegovina', 'BA'),
            (NEWSEQUENTIALID(), 'Botswana', 'BW'),
            (NEWSEQUENTIALID(), 'Bouvet Island', 'BV'),
            (NEWSEQUENTIALID(), 'Brazil', 'BR'),
            (NEWSEQUENTIALID(), 'British Indian Ocean Territory', 'IO'),
            (NEWSEQUENTIALID(), 'Brunei Darussalam', 'BN'),
            (NEWSEQUENTIALID(), 'Bulgaria', 'BG'),
            (NEWSEQUENTIALID(), 'Burkina Faso', 'BF'),
            (NEWSEQUENTIALID(), 'Burundi', 'BI'),
            (NEWSEQUENTIALID(), 'Cambodia', 'KH'),
            (NEWSEQUENTIALID(), 'Cameroon', 'CM'),
            (NEWSEQUENTIALID(), 'Canada', 'CA'),
            (NEWSEQUENTIALID(), 'Cape Verde', 'CV'),
            (NEWSEQUENTIALID(), 'Cayman Islands', 'KY'),
            (NEWSEQUENTIALID(), 'Central African Republic', 'CF'),
            (NEWSEQUENTIALID(), 'Chad', 'TD'),
            (NEWSEQUENTIALID(), 'Chile', 'CL'),
            (NEWSEQUENTIALID(), 'China', 'CN'),
            (NEWSEQUENTIALID(), 'Christmas Island', 'CX'),
            (NEWSEQUENTIALID(), 'Cocos (Keeling) Islands', 'CC'),
            (NEWSEQUENTIALID(), 'Colombia', 'CO'),
            (NEWSEQUENTIALID(), 'Comoros', 'KM'),
            (NEWSEQUENTIALID(), 'Congo', 'CG'),
            (NEWSEQUENTIALID(), 'Congo, Democratic Republic of the', 'CD'),
            (NEWSEQUENTIALID(), 'Cook Islands', 'CK'),
            (NEWSEQUENTIALID(), 'Costa Rica', 'CR'),
            (NEWSEQUENTIALID(), 'Cote D''Ivoire', 'CI'),
            (NEWSEQUENTIALID(), 'Croatia', 'HR'),
            (NEWSEQUENTIALID(), 'Cuba', 'CU'),
            (NEWSEQUENTIALID(), 'Cyprus', 'CY'),
            (NEWSEQUENTIALID(), 'Czech Republic', 'CZ'),
            (NEWSEQUENTIALID(), 'Denmark', 'DK'),
            (NEWSEQUENTIALID(), 'Djibouti', 'DJ'),
            (NEWSEQUENTIALID(), 'Dominica', 'DM'),
            (NEWSEQUENTIALID(), 'Dominican Republic', 'DO'),
            (NEWSEQUENTIALID(), 'Ecuador', 'EC'),
            (NEWSEQUENTIALID(), 'Egypt', 'EG'),
            (NEWSEQUENTIALID(), 'El Salvador', 'SV'),
            (NEWSEQUENTIALID(), 'Equatorial Guinea', 'GQ'),
            (NEWSEQUENTIALID(), 'Eritrea', 'ER'),
            (NEWSEQUENTIALID(), 'Estonia', 'EE'),
            (NEWSEQUENTIALID(), 'Ethiopia', 'ET'),
            (NEWSEQUENTIALID(), 'Falkland Islands (Malvinas)', 'FK'),
            (NEWSEQUENTIALID(), 'Faroe Islands', 'FO'),
            (NEWSEQUENTIALID(), 'Fiji', 'FJ'),
            (NEWSEQUENTIALID(), 'Finland', 'FI'),
            (NEWSEQUENTIALID(), 'France', 'FR'),
            (NEWSEQUENTIALID(), 'French Guiana', 'GF'),
            (NEWSEQUENTIALID(), 'French Polynesia', 'PF'),
            (NEWSEQUENTIALID(), 'French Southern Territories', 'TF'),
            (NEWSEQUENTIALID(), 'Gabon', 'GA'),
            (NEWSEQUENTIALID(), 'Gambia', 'GM'),
            (NEWSEQUENTIALID(), 'Georgia', 'GE'),
            (NEWSEQUENTIALID(), 'Germany', 'DE'),
            (NEWSEQUENTIALID(), 'Ghana', 'GH'),
            (NEWSEQUENTIALID(), 'Gibraltar', 'GI'),
            (NEWSEQUENTIALID(), 'Greece', 'GR'),
            (NEWSEQUENTIALID(), 'Greenland', 'GL'),
            (NEWSEQUENTIALID(), 'Grenada', 'GD'),
            (NEWSEQUENTIALID(), 'Guadeloupe', 'GP'),
            (NEWSEQUENTIALID(), 'Guam', 'GU'),
            (NEWSEQUENTIALID(), 'Guatemala', 'GT'),
            (NEWSEQUENTIALID(), 'Guernsey', 'GG'),
            (NEWSEQUENTIALID(), 'Guinea', 'GN'),
            (NEWSEQUENTIALID(), 'Guinea-Bissau', 'GW'),
            (NEWSEQUENTIALID(), 'Guyana', 'GY'),
            (NEWSEQUENTIALID(), 'Haiti', 'HT'),
            (NEWSEQUENTIALID(), 'Heard Island and Mcdonald Islands', 'HM'),
            (NEWSEQUENTIALID(), 'Holy See (Vatican City State)', 'VA'),
            (NEWSEQUENTIALID(), 'Honduras', 'HN'),
            (NEWSEQUENTIALID(), 'Hong Kong', 'HK'),
            (NEWSEQUENTIALID(), 'Hungary', 'HU'),
            (NEWSEQUENTIALID(), 'Iceland', 'IS'),
            (NEWSEQUENTIALID(), 'India', 'IN'),
            (NEWSEQUENTIALID(), 'Indonesia', 'ID'),
            (NEWSEQUENTIALID(), 'Iran, Islamic Republic of', 'IR'),
            (NEWSEQUENTIALID(), 'Iraq', 'IQ'),
            (NEWSEQUENTIALID(), 'Ireland', 'IE'),
            (NEWSEQUENTIALID(), 'Isle of Man', 'IM'),
            (NEWSEQUENTIALID(), 'Israel', 'IL'),
            (NEWSEQUENTIALID(), 'Italy', 'IT'),
            (NEWSEQUENTIALID(), 'Jamaica', 'JM'),
            (NEWSEQUENTIALID(), 'Japan', 'JP'),
            (NEWSEQUENTIALID(), 'Jersey', 'JE'),
            (NEWSEQUENTIALID(), 'Jordan', 'JO'),
            (NEWSEQUENTIALID(), 'Kazakhstan', 'KZ'),
            (NEWSEQUENTIALID(), 'Kenya', 'KE'),
            (NEWSEQUENTIALID(), 'Kiribati', 'KI'),
            (NEWSEQUENTIALID(), 'Korea, Democratic People''s Republic of', 'KP'),
            (NEWSEQUENTIALID(), 'Korea, Republic of', 'KR'),
            (NEWSEQUENTIALID(), 'Kuwait', 'KW'),
            (NEWSEQUENTIALID(), 'Kyrgyzstan', 'KG'),
            (NEWSEQUENTIALID(), 'Lao People''s Democratic Republic', 'LA'),
            (NEWSEQUENTIALID(), 'Latvia', 'LV'),
            (NEWSEQUENTIALID(), 'Lebanon', 'LB'),
            (NEWSEQUENTIALID(), 'Lesotho', 'LS'),
            (NEWSEQUENTIALID(), 'Liberia', 'LR'),
            (NEWSEQUENTIALID(), 'Libya', 'LY'),
            (NEWSEQUENTIALID(), 'Liechtenstein', 'LI'),
            (NEWSEQUENTIALID(), 'Lithuania', 'LT'),
            (NEWSEQUENTIALID(), 'Luxembourg', 'LU'),
            (NEWSEQUENTIALID(), 'Macao', 'MO'),
            (NEWSEQUENTIALID(), 'North Macedonia', 'MK'),
            (NEWSEQUENTIALID(), 'Madagascar', 'MG'),
            (NEWSEQUENTIALID(), 'Malawi', 'MW'),
            (NEWSEQUENTIALID(), 'Malaysia', 'MY'),
            (NEWSEQUENTIALID(), 'Maldives', 'MV'),
            (NEWSEQUENTIALID(), 'Mali', 'ML'),
            (NEWSEQUENTIALID(), 'Malta', 'MT'),
            (NEWSEQUENTIALID(), 'Marshall Islands', 'MH'),
            (NEWSEQUENTIALID(), 'Martinique', 'MQ'),
            (NEWSEQUENTIALID(), 'Mauritania', 'MR'),
            (NEWSEQUENTIALID(), 'Mauritius', 'MU'),
            (NEWSEQUENTIALID(), 'Mayotte', 'YT'),
            (NEWSEQUENTIALID(), 'Mexico', 'MX'),
            (NEWSEQUENTIALID(), 'Micronesia, Federated States of', 'FM'),
            (NEWSEQUENTIALID(), 'Moldova, Republic of', 'MD'),
            (NEWSEQUENTIALID(), 'Monaco', 'MC'),
            (NEWSEQUENTIALID(), 'Mongolia', 'MN'),
            (NEWSEQUENTIALID(), 'Montenegro', 'ME'),
            (NEWSEQUENTIALID(), 'Montserrat', 'MS'),
            (NEWSEQUENTIALID(), 'Morocco', 'MA'),
            (NEWSEQUENTIALID(), 'Mozambique', 'MZ'),
            (NEWSEQUENTIALID(), 'Myanmar', 'MM'),
            (NEWSEQUENTIALID(), 'Namibia', 'NA'),
            (NEWSEQUENTIALID(), 'Nauru', 'NR'),
            (NEWSEQUENTIALID(), 'Nepal', 'NP'),
            (NEWSEQUENTIALID(), 'Netherlands', 'NL'),
            (NEWSEQUENTIALID(), 'Curaçao', 'CW'),
            (NEWSEQUENTIALID(), 'Sint Maarten (Dutch part)', 'SX'),
            (NEWSEQUENTIALID(), 'Bonaire, Sint Eustatius and Saba', 'BQ'),
            (NEWSEQUENTIALID(), 'New Caledonia', 'NC'),
            (NEWSEQUENTIALID(), 'New Zealand', 'NZ'),
            (NEWSEQUENTIALID(), 'Nicaragua', 'NI'),
            (NEWSEQUENTIALID(), 'Niger', 'NE'),
            (NEWSEQUENTIALID(), 'Nigeria', 'NG'),
            (NEWSEQUENTIALID(), 'Niue', 'NU'),
            (NEWSEQUENTIALID(), 'Norfolk Island', 'NF'),
            (NEWSEQUENTIALID(), 'Northern Mariana Islands', 'MP'),
            (NEWSEQUENTIALID(), 'Norway', 'NO'),
            (NEWSEQUENTIALID(), 'Oman', 'OM'),
            (NEWSEQUENTIALID(), 'Pakistan', 'PK'),
            (NEWSEQUENTIALID(), 'Palau', 'PW'),
            (NEWSEQUENTIALID(), 'Palestinian Territory, Occupied', 'PS'),
            (NEWSEQUENTIALID(), 'Panama', 'PA'),
            (NEWSEQUENTIALID(), 'Papua New Guinea', 'PG'),
            (NEWSEQUENTIALID(), 'Paraguay', 'PY'),
            (NEWSEQUENTIALID(), 'Peru', 'PE'),
            (NEWSEQUENTIALID(), 'Philippines', 'PH'),
            (NEWSEQUENTIALID(), 'Pitcairn', 'PN'),
            (NEWSEQUENTIALID(), 'Poland', 'PL'),
            (NEWSEQUENTIALID(), 'Portugal', 'PT'),
            (NEWSEQUENTIALID(), 'Puerto Rico', 'PR'),
            (NEWSEQUENTIALID(), 'Qatar', 'QA'),
            (NEWSEQUENTIALID(), 'Reunion', 'RE'),
            (NEWSEQUENTIALID(), 'Romania', 'RO'),
            (NEWSEQUENTIALID(), 'Russian Federation', 'RU'),
            (NEWSEQUENTIALID(), 'Rwanda', 'RW'),
            (NEWSEQUENTIALID(), 'Saint Helena', 'SH'),
            (NEWSEQUENTIALID(), 'Saint Kitts and Nevis', 'KN'),
            (NEWSEQUENTIALID(), 'Saint Lucia', 'LC'),
            (NEWSEQUENTIALID(), 'Saint Pierre and Miquelon', 'PM'),
            (NEWSEQUENTIALID(), 'Saint Vincent and the Grenadines', 'VC'),
            (NEWSEQUENTIALID(), 'Samoa', 'WS'),
            (NEWSEQUENTIALID(), 'San Marino', 'SM'),
            (NEWSEQUENTIALID(), 'Sao Tome and Principe', 'ST'),
            (NEWSEQUENTIALID(), 'Saudi Arabia', 'SA'),
            (NEWSEQUENTIALID(), 'Senegal', 'SN'),
            (NEWSEQUENTIALID(), 'Serbia', 'RS'),
            (NEWSEQUENTIALID(), 'Seychelles', 'SC'),
            (NEWSEQUENTIALID(), 'Sierra Leone', 'SL'),
            (NEWSEQUENTIALID(), 'Singapore', 'SG'),
            (NEWSEQUENTIALID(), 'Slovakia', 'SK'),
            (NEWSEQUENTIALID(), 'Slovenia', 'SI'),
            (NEWSEQUENTIALID(), 'Solomon Islands', 'SB'),
            (NEWSEQUENTIALID(), 'Somalia', 'SO'),
            (NEWSEQUENTIALID(), 'South Africa', 'ZA'),
            (NEWSEQUENTIALID(), 'South Georgia and the South Sandwich Islands', 'GS'),
            (NEWSEQUENTIALID(), 'Spain', 'ES'),
            (NEWSEQUENTIALID(), 'Sri Lanka', 'LK'),
            (NEWSEQUENTIALID(), 'Sudan', 'SD'),
            (NEWSEQUENTIALID(), 'Suriname', 'SR'),
            (NEWSEQUENTIALID(), 'Svalbard and Jan Mayen', 'SJ'),
            (NEWSEQUENTIALID(), 'Swaziland', 'SZ'),
            (NEWSEQUENTIALID(), 'Sweden', 'SE'),
            (NEWSEQUENTIALID(), 'Switzerland', 'CH'),
            (NEWSEQUENTIALID(), 'Syrian Arab Republic', 'SY'),
            (NEWSEQUENTIALID(), 'Taiwan, Province of China', 'TW'),
            (NEWSEQUENTIALID(), 'Tajikistan', 'TJ'),
            (NEWSEQUENTIALID(), 'Tanzania, United Republic of', 'TZ'),
            (NEWSEQUENTIALID(), 'Thailand', 'TH'),
            (NEWSEQUENTIALID(), 'Timor-Leste', 'TL'),
            (NEWSEQUENTIALID(), 'Togo', 'TG'),
            (NEWSEQUENTIALID(), 'Tokelau', 'TK'),
            (NEWSEQUENTIALID(), 'Tonga', 'TO'),
            (NEWSEQUENTIALID(), 'Trinidad and Tobago', 'TT'),
            (NEWSEQUENTIALID(), 'Tunisia', 'TN'),
            (NEWSEQUENTIALID(), 'Turkey', 'TR'),
            (NEWSEQUENTIALID(), 'Turkmenistan', 'TM'),
            (NEWSEQUENTIALID(), 'Turks and Caicos Islands', 'TC'),
            (NEWSEQUENTIALID(), 'Tuvalu', 'TV'),
            (NEWSEQUENTIALID(), 'Uganda', 'UG'),
            (NEWSEQUENTIALID(), 'Ukraine', 'UA'),
            (NEWSEQUENTIALID(), 'United Arab Emirates', 'AE'),
            (NEWSEQUENTIALID(), 'United Kingdom', 'GB'),
            (NEWSEQUENTIALID(), 'United States', 'US'),
            (NEWSEQUENTIALID(), 'United States Minor Outlying Islands', 'UM'),
            (NEWSEQUENTIALID(), 'Uruguay', 'UY'),
            (NEWSEQUENTIALID(), 'Uzbekistan', 'UZ'),
            (NEWSEQUENTIALID(), 'Vanuatu', 'VU'),
            (NEWSEQUENTIALID(), 'Venezuela', 'VE'),
            (NEWSEQUENTIALID(), 'Viet Nam', 'VN'),
            (NEWSEQUENTIALID(), 'Virgin Islands, British', 'VG'),
            (NEWSEQUENTIALID(), 'Virgin Islands, U.S.', 'VI'),
            (NEWSEQUENTIALID(), 'Wallis and Futuna', 'WF'),
            (NEWSEQUENTIALID(), 'Western Sahara', 'EH'),
            (NEWSEQUENTIALID(), 'Yemen', 'YE'),
            (NEWSEQUENTIALID(), 'Zambia', 'ZM'),
            (NEWSEQUENTIALID(), 'Zimbabwe', 'ZW')
        ");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Remove all seeded country data
        migrationBuilder.Sql("DELETE FROM Countries");
    }
}
