<Project Sdk="Aspire.AppHost.Sdk/13.2.2">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>888f8594-d126-4858-9771-d366b0350777</UserSecretsId>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Identity\src\FrontendMentor.InvoiceApp.Identity.MigrationService\FrontendMentor.InvoiceApp.Identity.MigrationService.csproj" AspireProjectMetadataTypeName="IdentityMigrator" />
    <ProjectReference Include="..\FrontendMentor.InvoiceApp.AspireUtilities\FrontendMentor.InvoiceApp.AspireUtilities.csproj" IsAspireProjectResource="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>
</Project>
