name: Pull Request Verification

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
env:
  DOTNET_VERSION: 10.x
  BUILD_CONFIGURATION: Release
jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
           dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Test
        run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal --logger trx --results-directory ./test-results --collect:"XPlat Code Coverage"

      - name: Upload Test Results
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: ./test-results/**/*

      - name: Publish Test Results
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: Tests
          path: ./test-results/**/*.trx
          reporter: dotnet-trx

      - name: Formatting
        run: dotnet format -v detailed --verify-no-changes
